In [ ]:
import numpy as np
import pandas as pd

from src.regression import run_myfunc_w, run_constant_price

In [2]:
df = pd.read_csv('benchmark_results/opcodes/APPEND.csv')
run_myfunc_w(df)

(array([  97,  192, 2715]), 0.9984791193455083)

In [3]:
df = pd.read_csv('benchmark_results/opcodes/ASSERT.csv')
run_myfunc_w(df, power=4.0)

(array([  99,    9, 1847]), 0.9963984196073249)

In [4]:
df = pd.read_csv('benchmark_results/opcodes/CAT.csv')
run_myfunc_w(df)

(array([   8, 2706]), 0.9966775084118622)

In [5]:
df = pd.read_csv('benchmark_results/opcodes/CLEAR.csv')
run_myfunc_w(df, power=3.0)

(array([  93,  -15, 1515]), 0.9865534456599984)

In [6]:
df = pd.read_csv('benchmark_results/opcodes/CLEARITEMS.csv')
run_myfunc_w(df)

(array([ 103, 1455]), 0.9923474635352815)

In [7]:
df = pd.read_csv('benchmark_results/opcodes/CONVERT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Any'], drop_columns=['type', 'length']))
print(run_myfunc_w(df, handler=lambda df: df.loc[(df['type'] == 'Any') | (df['type'] == 'Array')], drop_columns=['type']))
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'ByteString'], drop_columns=['type', 'refsdelta']))

(array([  78, 1610]), 0.9999891350866396)
(array([  77,  134, 3218]), 0.9999118728833346)
(array([   7, 3417]), 0.9948732866123206)


In [8]:
df = pd.read_csv('benchmark_results/opcodes/DROP.csv')
run_myfunc_w(df)

(array([  99, 1486]), 0.9999616583290638)

In [9]:
df = pd.read_csv('benchmark_results/opcodes/ENDFINALLY.csv')
run_myfunc_w(df)

(array([  93, 1137]), 0.9993540285410546)

In [10]:
df = pd.read_csv('benchmark_results/opcodes/HASKEY.csv')
run_myfunc_w(df)

(array([  99, 2575]), 0.9999178734882065)

In [11]:
df = pd.read_csv('benchmark_results/opcodes/INITSLOT.csv')
run_myfunc_w(df)

(array([  67,  160, 1702]), 0.9856241421634455)

In [12]:
df = pd.read_csv('benchmark_results/opcodes/ISNULL.csv')
run_myfunc_w(df)

(array([  97, 1236]), 0.9998926474618235)

In [13]:
df = pd.read_csv('benchmark_results/opcodes/ISTYPE.csv')
run_myfunc_w(df)

(array([  97, 1154]), 0.9998958761752024)

In [14]:
df = pd.read_csv('benchmark_results/opcodes/KEYS.csv')
run_myfunc_w(df)

(array([  96,  167, 2039]), 0.9992419687435024)

In [15]:
df = pd.read_csv('benchmark_results/opcodes/MEMCPY.csv')
run_myfunc_w(df)

(array([   1, 3514]), 0.9976381810258412)

In [16]:
# у них должны быть одинаковые свободные члены
df = pd.read_csv('benchmark_results/opcodes/NEWARRAYT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Any'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/NEWARRAYT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'ByteString'], drop_columns=['type']))

(array([ 124, 2529]), 0.9941544557558046)
(array([ 134, 3108]), 0.9975894656331358)


In [17]:
df = pd.read_csv('benchmark_results/opcodes/NEWBUFFER.csv')
run_myfunc_w(df)

(array([   6, 2507]), 0.9842623417216284)

In [18]:
df = pd.read_csv('benchmark_results/opcodes/PACK.csv')
run_myfunc_w(df)

(array([ 173, 2649]), 0.9869225328768629)

In [19]:
df = pd.read_csv('benchmark_results/opcodes/PACKMAP.csv')
run_myfunc_w(df, power=3.5)

(array([  80, 5281, 3481]), 0.9995953894669359)

In [20]:
df = pd.read_csv('benchmark_results/opcodes/PICKITEM.csv')
run_myfunc_w(df, power=3.0)

(array([  91,    6, 2751]), 0.9826647731123996)

In [21]:
df = pd.read_csv('benchmark_results/opcodes/POPITEM.csv')
run_myfunc_w(df, power=1.5)

(array([  91, 3078]), 0.9709481136643807)

In [22]:
# некорректные свободные члены
df = pd.read_csv('benchmark_results/opcodes/REMOVE.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Array'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/REMOVE.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Map'], drop_columns=['type']))

(array([  98,    9, 1991]), 0.9997662710789825)
(array([  96,  706, 6776]), 0.9856757072755092)


In [23]:
df = pd.read_csv('benchmark_results/opcodes/REVERSEITEMS.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Array'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/REVERSEITEMS.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Buffer'], drop_columns=['type', 'refsdelta']))

(array([  98,   19, 2043]), 0.9999718525695899)
(array([   9, 1690]), 0.9999512221590083)


In [24]:
df = pd.read_csv('benchmark_results/opcodes/REVERSEN.csv')
run_myfunc_w(df)

(array([  19, 1702]), 0.9989287831375325)

In [25]:
df = pd.read_csv('benchmark_results/opcodes/ROLL.csv')
run_myfunc_w(df)

(array([   5, 1910]), 0.8739258349860559)

In [26]:
df = pd.read_csv('benchmark_results/opcodes/SETITEM.csv')
run_myfunc_w(df)

(array([  96,  149, 2390]), 0.9995095059611883)

In [27]:
df = pd.read_csv('benchmark_results/opcodes/SIZE.csv')
run_myfunc_w(df)

(array([ 100, 2693]), 0.9996362207138568)

In [28]:
df = pd.read_csv('benchmark_results/opcodes/ST.csv')
run_myfunc_w(df)

(array([  98, 1599]), 0.9999450035176572)

In [29]:
df = pd.read_csv('benchmark_results/opcodes/SUBSTR.csv')
run_myfunc_w(df)

(array([   7, 2908]), 0.9922615244242385)

In [30]:
df = pd.read_csv('benchmark_results/opcodes/THROW.csv')
run_myfunc_w(df)

(array([  84, 1742]), 0.9955935316589891)

In [31]:
df = pd.read_csv('benchmark_results/opcodes/UNPACK.csv')
run_myfunc_w(df)

(array([ 254, 2604]), 0.9745961081469285)

In [32]:
# некорректный свободный член
df = pd.read_csv('benchmark_results/opcodes/VALUES.csv')
run_myfunc_w(df)

(array([  86,  312,  168, 4758]), 0.9992847536019204)

In [33]:
df = pd.read_csv('benchmark_results/opcodes/XDROP.csv')
run_myfunc_w(df)

(array([  98,    6, 1791]), 0.9999667583238937)

## Interops

In [34]:
df = pd.read_csv('benchmark_results/interops/BurnGas.csv')
run_constant_price(df)

np.int64(1706)

In [35]:
df = pd.read_csv('benchmark_results/interops/CheckMultisig.csv')
run_myfunc_w(df)

(array([ 243460, 1475852]), 0.9999727451791555)

In [36]:
df = pd.read_csv('benchmark_results/interops/CheckSig.csv')
run_constant_price(df)

np.int64(470088)

In [37]:
df = pd.read_csv('benchmark_results/interops/ContractCall.csv')
run_myfunc_w(df)

(array([    1,    91,    77,     7, 13655]), 0.9645385655966231)

In [11]:
# маленькая зашумлённая выборка, r2 нестабилен на train/test разбиении
df = pd.read_csv('benchmark_results/interops/ContractCallNative.csv')
run_myfunc_w(df)

(array([ 168, 2890]), -2.2196240748850316)

In [39]:
df = pd.read_csv('benchmark_results/interops/CreateMultisigAccount.csv')
run_myfunc_w(df)

(array([ 1911, 79005]), 0.9964829998478567)

In [40]:
df = pd.read_csv('benchmark_results/interops/CreateStandardAccount.csv')
run_constant_price(df)

np.int64(9362)

In [41]:
df = pd.read_csv('benchmark_results/interops/CurrentSigners.csv')
run_myfunc_w(df)

(array([  2042, 194895]), 0.9950204911145818)

In [42]:
df = pd.read_csv('benchmark_results/interops/GasLeft.csv')
run_constant_price(df)

np.int64(1862)

In [43]:
df = pd.read_csv('benchmark_results/interops/GetAddressVersion.csv')
run_constant_price(df)

np.int64(1838)

In [44]:
df = pd.read_csv('benchmark_results/interops/GetCallFlags.csv')
run_constant_price(df)

np.int64(1450)

In [45]:
df = pd.read_csv('benchmark_results/interops/GetCallingScriptHash.csv')
run_constant_price(df)

np.int64(2019)

In [46]:
df = pd.read_csv('benchmark_results/interops/GetEntryScriptHash.csv')
run_constant_price(df)

np.int64(2188)

In [47]:
df = pd.read_csv('benchmark_results/interops/GetExecutingScriptHash.csv')
run_constant_price(df)

np.int64(2038)

In [48]:
df = pd.read_csv('benchmark_results/interops/GetInvocationCounter.csv')
run_constant_price(df)

np.int64(2356)

In [49]:
df = pd.read_csv('benchmark_results/interops/GetNetwork.csv')
run_constant_price(df)

np.int64(3425)

In [50]:
df = pd.read_csv('benchmark_results/interops/GetNotifications.csv')
run_myfunc_w(df)

(array([1379,   22, 4349]), 0.9998998966799412)

In [51]:
df = pd.read_csv('benchmark_results/interops/GetRandom.csv')
run_constant_price(df)

np.int64(4181)

In [52]:
df = pd.read_csv('benchmark_results/interops/GetScriptContainer.csv')
run_constant_price(df)

np.int64(7788)

In [53]:
df = pd.read_csv('benchmark_results/interops/GetTime.csv')
run_constant_price(df)

np.int64(2206)

In [54]:
df = pd.read_csv('benchmark_results/interops/GetTrigger.csv')
run_constant_price(df)

np.int64(2519)

In [55]:
df = pd.read_csv('benchmark_results/interops/IteratorNext.csv')
run_constant_price(df)

np.int64(2219)

In [56]:
df = pd.read_csv('benchmark_results/interops/IteratorValue.csv')
run_myfunc_w(df)

(array([  160,     1, 10588]), 0.9735697196192598)

In [57]:
# отрицательный коэффициент при refs_delta — вероятно, наложены независимые серии измерений
df = pd.read_csv('benchmark_results/interops/LoadScript.csv')
run_myfunc_w(df)

(array([   39,    50,   -10, 62345]), 0.9783835442272212)

In [58]:
df = pd.read_csv('benchmark_results/interops/Log.csv')
run_constant_price(df)

np.int64(7025)

In [59]:
# отрицательный коэффициент при events_count — вероятно, наложены независимые серии измерений
df = pd.read_csv('benchmark_results/interops/Notify.csv')
run_myfunc_w(df)

(array([  -11,   363, 30620]), 0.989896154496218)

In [60]:
df = pd.read_csv('benchmark_results/interops/Platform.csv')
run_constant_price(df)

np.int64(3775)