In [253]:
import numpy as np
import pandas as pd

from src.regression import run_myfunc_w, run_constant_price

In [254]:
df = pd.read_csv('benchmark_results/opcodes/APPEND.csv')
run_myfunc_w(df)

(array([  97,  192, 2715]), 0.9984791193455083)

In [255]:
df = pd.read_csv('benchmark_results/opcodes/ASSERT.csv')
run_myfunc_w(df, power=4.0)

(array([  99,    9, 1847]), 0.9963984196073249)

In [256]:
df = pd.read_csv('benchmark_results/opcodes/CAT.csv')
run_myfunc_w(df)

(array([   8, 2706]), 0.9966775084118622)

In [257]:
df = pd.read_csv('benchmark_results/opcodes/CLEAR.csv')
run_myfunc_w(df, power=3.0)

(array([  93,  -15, 1515]), 0.9865534456599984)

In [258]:
df = pd.read_csv('benchmark_results/opcodes/CLEARITEMS.csv')
run_myfunc_w(df)

(array([ 103, 1455]), 0.9923474635352815)

In [259]:
df = pd.read_csv('benchmark_results/opcodes/CONVERT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Any'], drop_columns=['type', 'length']))
print(run_myfunc_w(df, handler=lambda df: df.loc[(df['type'] == 'Any') | (df['type'] == 'Array')], drop_columns=['type']))
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'ByteString'], drop_columns=['type', 'refsdelta']))

(array([  78, 1610]), 0.9999891350866396)
(array([  77,  134, 3218]), 0.9999118728833346)
(array([   7, 3417]), 0.9948732866123206)


In [260]:
df = pd.read_csv('benchmark_results/opcodes/DROP.csv')
run_myfunc_w(df)

(array([  99, 1486]), 0.9999616583290638)

In [261]:
df = pd.read_csv('benchmark_results/opcodes/ENDFINALLY.csv')
run_myfunc_w(df)

(array([  93, 1137]), 0.9993540285410546)

In [262]:
df = pd.read_csv('benchmark_results/opcodes/HASKEY.csv')
run_myfunc_w(df)

(array([  99, 2575]), 0.9999178734882065)

In [263]:
df = pd.read_csv('benchmark_results/opcodes/INITSLOT.csv')
run_myfunc_w(df)

(array([  67,  160, 1702]), 0.9856241421634455)

In [264]:
df = pd.read_csv('benchmark_results/opcodes/ISNULL.csv')
run_myfunc_w(df)

(array([  97, 1236]), 0.9998926474618235)

In [265]:
df = pd.read_csv('benchmark_results/opcodes/ISTYPE.csv')
run_myfunc_w(df)

(array([  97, 1154]), 0.9998958761752024)

In [266]:
df = pd.read_csv('benchmark_results/opcodes/KEYS.csv')
run_myfunc_w(df)

(array([  96,  167, 2039]), 0.9992419687435024)

In [267]:
df = pd.read_csv('benchmark_results/opcodes/MEMCPY.csv')
run_myfunc_w(df)

(array([   1, 3514]), 0.9976381810258412)

In [268]:
# у них должны быть одинаковые свободные члены
df = pd.read_csv('benchmark_results/opcodes/NEWARRAYT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Any'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/NEWARRAYT.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'ByteString'], drop_columns=['type']))

(array([ 124, 2529]), 0.9941544557558046)
(array([ 134, 3108]), 0.9975894656331358)


In [269]:
df = pd.read_csv('benchmark_results/opcodes/NEWBUFFER.csv')
run_myfunc_w(df)

(array([   6, 2507]), 0.9842623417216284)

In [270]:
df = pd.read_csv('benchmark_results/opcodes/PACK.csv')
run_myfunc_w(df)

(array([ 173, 2649]), 0.9869225328768629)

In [271]:
df = pd.read_csv('benchmark_results/opcodes/PACKMAP.csv')
run_myfunc_w(df, power=3.5)

(array([  80, 5281, 3481]), 0.9995953894669359)

In [272]:
df = pd.read_csv('benchmark_results/opcodes/PICKITEM.csv')
run_myfunc_w(df, power=3.0)

(array([  91,    6, 2751]), 0.9826647731123996)

In [273]:
df = pd.read_csv('benchmark_results/opcodes/POPITEM.csv')
run_myfunc_w(df, power=1.5)

(array([  91, 3078]), 0.9709481136643807)

In [274]:
# некорректные свободные члены
df = pd.read_csv('benchmark_results/opcodes/REMOVE.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Array'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/REMOVE.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Map'], drop_columns=['type']))

(array([  98,    9, 1991]), 0.9997662710789825)
(array([  96,  706, 6776]), 0.9856757072755092)


In [275]:
df = pd.read_csv('benchmark_results/opcodes/REVERSEITEMS.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Array'], drop_columns=['type']))
df = pd.read_csv('benchmark_results/opcodes/REVERSEITEMS.csv')
print(run_myfunc_w(df, handler=lambda df: df[df['type'] == 'Buffer'], drop_columns=['type', 'refsdelta']))

(array([  98,   19, 2043]), 0.9999718525695899)
(array([   9, 1690]), 0.9999512221590083)


In [276]:
df = pd.read_csv('benchmark_results/opcodes/REVERSEN.csv')
run_myfunc_w(df)

(array([  19, 1702]), 0.9989287831375325)

In [277]:
df = pd.read_csv('benchmark_results/opcodes/ROLL.csv')
run_myfunc_w(df)

(array([   5, 1910]), 0.8739258349860559)

In [278]:
df = pd.read_csv('benchmark_results/opcodes/SETITEM.csv')
run_myfunc_w(df)

(array([  96,  149, 2390]), 0.9995095059611883)

In [279]:
df = pd.read_csv('benchmark_results/opcodes/SIZE.csv')
run_myfunc_w(df)

(array([ 100, 2693]), 0.9996362207138568)

In [280]:
df = pd.read_csv('benchmark_results/opcodes/ST.csv')
run_myfunc_w(df)

(array([  98, 1599]), 0.9999450035176572)

In [281]:
df = pd.read_csv('benchmark_results/opcodes/SUBSTR.csv')
run_myfunc_w(df)

(array([   7, 2908]), 0.9922615244242385)

In [282]:
df = pd.read_csv('benchmark_results/opcodes/THROW.csv')
run_myfunc_w(df)

(array([  84, 1742]), 0.9955935316589891)

In [283]:
df = pd.read_csv('benchmark_results/opcodes/UNPACK.csv')
run_myfunc_w(df)

(array([ 254, 2604]), 0.9745961081469285)

In [284]:
# некорректный свободный член
df = pd.read_csv('benchmark_results/opcodes/VALUES.csv')
run_myfunc_w(df)

(array([  86,  312,  168, 4758]), 0.9992847536019204)

In [285]:
df = pd.read_csv('benchmark_results/opcodes/XDROP.csv')
run_myfunc_w(df)

(array([  98,    6, 1791]), 0.9999667583238937)

## Interops

In [286]:
df = pd.read_csv('benchmark_results/interops/BurnGas.csv')
run_constant_price(df)

np.int64(3067)

In [287]:
df = pd.read_csv('benchmark_results/interops/CheckMultisig.csv')
run_myfunc_w(df)

(array([1309030, 1232349]), 0.9997941025907138)

In [288]:
df = pd.read_csv('benchmark_results/interops/CheckMultisigDummy.csv')
run_myfunc_w(df)

(array([2273675,  232030]), 0.9999988438507669)

In [289]:
df = pd.read_csv('benchmark_results/interops/CheckSig.csv')
run_constant_price(df)

np.int64(2458133)

In [290]:
df = pd.read_csv('benchmark_results/interops/CheckWitness.csv')
run_myfunc_w(df)

(array([305636,   3124,  42888]), 0.9992671135015958)

In [291]:
df = pd.read_csv('benchmark_results/interops/ContractCall.csv')
run_myfunc_w(df)

(array([0, 0, 0, 0, 0, 0]), 1.0)

In [292]:
df = pd.read_csv('benchmark_results/interops/ContractCallNative.csv')
run_myfunc_w(df)

(array([  806, 60127]), 0.9034997543163704)

In [293]:
df = pd.read_csv('benchmark_results/interops/CreateMultisigAccount.csv')
run_myfunc_w(df)

(array([10866, 66135]), 0.982490806540673)

In [294]:
df = pd.read_csv('benchmark_results/interops/CreateStandardAccount.csv')
run_constant_price(df)

np.int64(51667)

In [295]:
df = pd.read_csv('benchmark_results/interops/CurrentSigners.csv')
run_myfunc_w(df)

(array([33668567,    43033]), 0.997091023713319)

In [296]:
df = pd.read_csv('benchmark_results/interops/GasLeft.csv')
run_constant_price(df)

np.int64(8900)

In [297]:
df = pd.read_csv('benchmark_results/interops/GetAddressVersion.csv')
run_constant_price(df)

np.int64(8867)

In [298]:
df = pd.read_csv('benchmark_results/interops/GetCallFlags.csv')
run_constant_price(df)

np.int64(12367)

In [299]:
df = pd.read_csv('benchmark_results/interops/GetCallingScriptHash.csv')
run_constant_price(df)

np.int64(9567)

In [300]:
df = pd.read_csv('benchmark_results/interops/GetEntryScriptHash.csv')
run_constant_price(df)

np.int64(9900)

In [301]:
df = pd.read_csv('benchmark_results/interops/GetExecutingScriptHash.csv')
run_constant_price(df)

np.int64(9900)

In [302]:
df = pd.read_csv('benchmark_results/interops/GetInvocationCounter.csv')
run_constant_price(df)

np.int64(10267)

In [303]:
df = pd.read_csv('benchmark_results/interops/GetNetwork.csv')
run_constant_price(df)

np.int64(9833)

In [304]:
df = pd.read_csv('benchmark_results/interops/GetNotifications.csv')
run_myfunc_w(df)

(array([ 7291,   129, 16676]), 0.9982355451824708)

In [305]:
df = pd.read_csv('benchmark_results/interops/GetRandom.csv')
run_constant_price(df)

np.int64(15833)

In [306]:
df = pd.read_csv('benchmark_results/interops/GetScriptContainer.csv')
run_constant_price(df)

np.int64(36533)

In [307]:
df = pd.read_csv('benchmark_results/interops/GetTime.csv')
run_constant_price(df)

np.int64(9033)

In [308]:
df = pd.read_csv('benchmark_results/interops/GetTrigger.csv')
run_constant_price(df)

np.int64(8700)

In [309]:
df = pd.read_csv('benchmark_results/interops/IteratorNext.csv')
run_constant_price(df)

np.int64(6300)

In [310]:
df = pd.read_csv('benchmark_results/interops/IteratorValue.csv')
run_myfunc_w(df)

(array([  845,     5, 21222]), 0.9946742635756115)

In [311]:
df = pd.read_csv('benchmark_results/interops/LoadScript.csv')
run_myfunc_w(df)

(array([0, 0, 0, 0]), 1.0)

In [312]:
df = pd.read_csv('benchmark_results/interops/Log.csv')
run_constant_price(df)

np.int64(31767)

In [313]:
df = pd.read_csv('benchmark_results/interops/Notify.csv')
run_myfunc_w(df)

(array([   82,  2143, 16201, 29876]), 0.9929078787275476)

In [314]:
df = pd.read_csv('benchmark_results/interops/Platform.csv')
run_constant_price(df)

np.int64(8867)

## Interop pricing consistency

In [315]:
rows = [line.strip('|\n').split('|') for line in open('interop_benchmarks.md') if line.startswith('| `')]
df = pd.DataFrame(
    [[float(old), float(new)] for _, old, new in rows],
    columns=['Old model', 'New model'],
    index=[name.strip(' `') for name, _, _ in rows],
)
pd.DataFrame({'mean': df.mean(), 'std': df.std(), 'cv': df.std() / df.mean(), 'max/min': df.max() / df.min()})

,mean,std,cv,max/min
Old model,65.585802,295.551755,4.506337,1.086733e+06
New model,14.294335,13.565245,0.948994,2.262821e+03
